name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Setup environment variables
      run: |
        APP_VERSION=`cat VERSION`
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

    - name: Build
      run: cd script && sh build-binary.sh

    - name: Package Binaries
      run: |
        cd _
        sudo tar -cvzf wheel-linux-amd64.tar.gz --directory=linux-amd64 .
        sudo tar -cvzf wheel-linux-arm64.tar.gz --directory=linux-arm64 .
        cd windows-amd64 && sudo zip -r ../wheel-windows-amd64.zip * && cd ..
        cd darwin-amd64 && sudo zip -r ../wheel-darwin-amd64.zip * && cd ..
    
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      name: Remove existing release for current version
      with:
        delete_release: true
        tag_name: ${{ env.APP_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      name: publish release for current version
      with:
        artifacts: "_/*.gz,_/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        removeArtifacts: true
        tag: ${{ env.APP_VERSION }}
        allowUpdates: true
        name: ${{ env.APP_VERSION }}
        commit: master
        artifactErrorsFailBuild: true
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      name: Remove existing release for latest version
      with:
        delete_release: true
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      name: publish release for latest version
      with:
        artifacts: "_/*.gz,_/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        removeArtifacts: true
        tag: latest
        allowUpdates: true
        name: latest
        commit: master
        artifactErrorsFailBuild: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker images
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          cnbian/wheel:${{ env.APP_VERSION }}
          cnbian/wheel:latest
          ghcr.io/jerrybian/wheel:${{ env.APP_VERSION }}
          ghcr.io/jerrybian/wheel:latest